# POST http://localhost:5000/api/students/add-student 
# content-type: application/json

# {
#     "name": "Bhargab Nath"
# }

# POST http://localhost:5000/api/admin/signup 
# content-type: application/json

# {
#     "email": "rahulsingh@gmail.com",
#     "password": "123456"
# }

# POST http://localhost:5000/api/admin/login 
# content-type: application/json

# {
#     "email": "rahulsingh@gmail.com",
#     "password": "123456"
# }

POST http://localhost:5000/api/students/61c42429ec14b6731e79e66b/add-course
content-type: application/json

{
    "name": "Introduction to Operating System",
    "code": "CS-303"
}